events { worker_connections 1024; }

http {
    upstream backend_servers {
        server backend1:8090; # Puerto interno de tu app Spring
        server backend2:8090;
    }

    server {
        listen 80; # Nginx escucha en el 80 del contenedor
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}