events { worker_connections 1024; }

http {
    upstream backend_servers {
        server backend1:8080; # Puerto interno de tu app Spring
        server backend2:8080;
    }

    server {
        listen 80; # Nginx escucha en el 80 del contenedor
        location / {
            proxy_pass http://backend_servers;
            
            # Cabeceras vitales para que Spring Boot "entienda" de dónde viene la petición
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Esto asegura que Nginx no intercepte los errores y deje que Java responda el CORS
            proxy_intercept_errors off; 
        }
    }
}