spring.application.name=demo

# Puerto del servidor
server.port=8080

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/travel_agency_db
spring.datasource.username=user
spring.datasource.password=password

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL del Realm (coincide con TravelAgencyRealm de tu .env)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/TravelAgencyRealm

# URL para obtener las llaves publicas de validacion
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/TravelAgencyRealm/protocol/openid-connect/certs

keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}

keycloak.client-id=${KEYCLOAK_CLIENT_ID}

keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}